import { AIMediaItemDownloadConfirmation } from '@models/swagger/App/Domain/AI/Entities/MediaItems/DownloadConfirmation/AIMediaItemDownloadConfirmation';
import { PostMediaItemSetting } from '@models/swagger/App/Domain/Presence/Entities/Locations/Posts/MediaItems/PostMediaItemSetting';

export const PostMediaItemSettingsObjectType = {
  App_Domain_Presence_Entities_Locations_Posts_MediaItems_PostMediaItemSettings:
    'App\\Domain\\Presence\\Entities\\Locations\\Posts\\MediaItems\\PostMediaItemSettings',
};

export const PostMediaItemSettingsObjectTypeStrict = {
  App_Domain_Presence_Entities_Locations_Posts_MediaItems_PostMediaItemSettings:
    'App\\Domain\\Presence\\Entities\\Locations\\Posts\\MediaItems\\PostMediaItemSettings',
} as const;

export type PostMediaItemSettings = {
  facebook?: PostMediaItemSetting;
  instagram?: PostMediaItemSetting;
  linkedin?: PostMediaItemSetting;
  x?: PostMediaItemSetting;
  downloadConfirmation?: AIMediaItemDownloadConfirmation;
  /**
   * If true, the media item has been removed from Front-end
   */
  removed?: boolean;
  /**
   * If true, the media item is generated by AI
   */
  isAIGenerated?: boolean;
  /**
   * URL of the original media item
   */
  importLink?: string;
  /**
   * The fully qualified class name of the object
   */
  objectType: (typeof PostMediaItemSettingsObjectType)[keyof typeof PostMediaItemSettingsObjectType];
};
