import { AIMediaItemDownloadConfirmation } from '@models/swagger/App/Domain/AI/Entities/MediaItems/DownloadConfirmation/AIMediaItemDownloadConfirmation';
import { PostMediaItemSetting } from '@models/swagger/App/Domain/Presence/Entities/Locations/Posts/MediaItems/PostMediaItemSetting';

export const PostMediaItemThumbnailSettingsObjectType = {
  App_Domain_Presence_Entities_Locations_Posts_MediaItems_PostMediaItemThumbnailSettings:
    'App\\Domain\\Presence\\Entities\\Locations\\Posts\\MediaItems\\PostMediaItemThumbnailSettings',
};

export const PostMediaItemThumbnailSettingsObjectTypeStrict = {
  App_Domain_Presence_Entities_Locations_Posts_MediaItems_PostMediaItemThumbnailSettings:
    'App\\Domain\\Presence\\Entities\\Locations\\Posts\\MediaItems\\PostMediaItemThumbnailSettings',
} as const;

export type PostMediaItemThumbnailSettings = {
  /**
   * The parent PostMediaItemId set for photo thumbnails related to the video media item
   */
  parentPostMediaItemId?: number;
  /**
   * The duration of the video in format MM:SS
   */
  videoDuration?: string;
  /**
   * The size of the video in bits
   */
  videoSize?: string;
  facebook?: PostMediaItemSetting;
  instagram?: PostMediaItemSetting;
  linkedin?: PostMediaItemSetting;
  x?: PostMediaItemSetting;
  downloadConfirmation?: AIMediaItemDownloadConfirmation;
  /**
   * If true, the media item has been removed from Front-end
   */
  removed?: boolean;
  /**
   * If true, the media item is generated by AI
   */
  isAIGenerated?: boolean;
  /**
   * URL of the original media item
   */
  importLink?: string;
  /**
   * The fully qualified class name of the object
   */
  objectType: (typeof PostMediaItemThumbnailSettingsObjectType)[keyof typeof PostMediaItemThumbnailSettingsObjectType];
};
