import { AIMediaItemDownloadConfirmation } from '@models/swagger/App/Domain/AI/Entities/MediaItems/DownloadConfirmation/AIMediaItemDownloadConfirmation';
import { PostMediaItemSetting } from '@models/swagger/App/Domain/Presence/Entities/Locations/Posts/MediaItems/PostMediaItemSetting';

export const PostMediaItemVideoSettingsObjectType = {
  App_Domain_Presence_Entities_Locations_Posts_MediaItems_PostMediaItemVideoSettings:
    'App\\Domain\\Presence\\Entities\\Locations\\Posts\\MediaItems\\PostMediaItemVideoSettings',
};

export const PostMediaItemVideoSettingsObjectTypeStrict = {
  App_Domain_Presence_Entities_Locations_Posts_MediaItems_PostMediaItemVideoSettings:
    'App\\Domain\\Presence\\Entities\\Locations\\Posts\\MediaItems\\PostMediaItemVideoSettings',
} as const;

export type PostMediaItemVideoSettings = {
  /**
   * The duration of the video in format MM:SS
   */
  videoDuration?: string;
  /**
   * The size of the video in bits
   */
  videoSize?: string;
  facebook?: PostMediaItemSetting;
  instagram?: PostMediaItemSetting;
  linkedin?: PostMediaItemSetting;
  x?: PostMediaItemSetting;
  downloadConfirmation?: AIMediaItemDownloadConfirmation;
  /**
   * If true, the media item has been removed from Front-end
   */
  removed?: boolean;
  /**
   * If true, the media item is generated by AI
   */
  isAIGenerated?: boolean;
  /**
   * URL of the original media item
   */
  importLink?: string;
  /**
   * The fully qualified class name of the object
   */
  objectType: (typeof PostMediaItemVideoSettingsObjectType)[keyof typeof PostMediaItemVideoSettingsObjectType];
};
