export const statusBadgeGetAllStates = () =>
  [
    'danger',
    'info',
    'warning',
    'success',
    'publishing',
    'publishingStatic',
    'neutral',
    'limitExcedeed',
    'live',
    'pending_verification',
    'not_approved',
    'scheduled',
    'past',
    'published',
    'draft',
    'published_variant',
    'active',
    'paused',
    'deleted',
    'archived',
    'sent',
    'queued',
    'not_sent',
    'connected',
    'ai',
  ] as const;
