import { Account } from '@models/swagger/App/Domain/Common/Entities/Accounts/Account';
import { Project } from '@models/swagger/App/Domain/Common/Entities/Projects/Project';
import { ChangeHistory } from '@models/swagger/DDD/Domain/Base/Entities/ChangeHistory/ChangeHistory';

export const AccountAICostPrompt = {
  'APP.TRANSLATIONS.MULTILOCALE.INFORMAL': 'APP.TRANSLATIONS.MULTILOCALE.INFORMAL',
  'APP.TRANSLATIONS.SINGLELOCALE.INFORMAL': 'APP.TRANSLATIONS.SINGLELOCALE.INFORMAL',
  'APP.TRANSLATIONS.SINGLELOCALE.FORMAL': 'APP.TRANSLATIONS.SINGLELOCALE.FORMAL',
  'APP.GENERATED.REVIEW.REPLY': 'APP.GENERATED.REVIEW.REPLY',
  'APP.GENERATED.REVIEW.REPLY.ADVANCED': 'APP.GENERATED.REVIEW.REPLY.ADVANCED',
  'APP.REPUTATION.REVIEWS.REPUTATION.TOPICS': 'APP.REPUTATION.REVIEWS.REPUTATION.TOPICS',
  'APP.REPUTATION.REVIEWS.REPUTATION.DIMENSIONS': 'APP.REPUTATION.REVIEWS.REPUTATION.DIMENSIONS',
  'APP.REPUTATION.SUMMARY': 'APP.REPUTATION.SUMMARY',
  'APP.GENERATED.POST.INSTRUCTION': 'APP.GENERATED.POST.INSTRUCTION',
  'APP.GENERATED.POST.COMPETITORS': 'APP.GENERATED.POST.COMPETITORS',
  'APP.GENERATED.COMMENT.REPLY': 'APP.GENERATED.COMMENT.REPLY',
  'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION': 'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION',
  'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION.ANALYSIS': 'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION.ANALYSIS',
  'APP.AI.TEXT.KEYWORDS': 'APP.AI.TEXT.KEYWORDS',
  'APP.AI.PROMPT.INJECTION.DETECTION': 'APP.AI.PROMPT.INJECTION.DETECTION',
  'APP.AI.EMAIL_CONTENT.MODERATION': 'APP.AI.EMAIL_CONTENT.MODERATION',
  'APP.TRANSLATIONKEY.UNDERSTANDABILITY': 'APP.TRANSLATIONKEY.UNDERSTANDABILITY',
  'APP.AI.TEXT.ADJUST': 'APP.AI.TEXT.ADJUST',
  'APP.AI.TEXT.ADJUSTMENT': 'APP.AI.TEXT.ADJUSTMENT',
  'APP.GENERATED.EVENT.INSTRUCTION': 'APP.GENERATED.EVENT.INSTRUCTION',
  'APP.SEO.TEXT.OPTIMISATIONS': 'APP.SEO.TEXT.OPTIMISATIONS',
  'APP.SEO.TEXT.OPTIMISATION.LEVEL': 'APP.SEO.TEXT.OPTIMISATION.LEVEL',
  'APP.SEO.PROPOSE_KEYWORDS': 'APP.SEO.PROPOSE_KEYWORDS',
  'APP.SEO.PROPOSE_KEYWORDS.WEBSITE_CONTENT.ELEMENTS': 'APP.SEO.PROPOSE_KEYWORDS.WEBSITE_CONTENT.ELEMENTS',
  'APP.OPENING_HOURS.PROPOSE': 'APP.OPENING_HOURS.PROPOSE',
  'APP.DESCRIPTION.PROPOSE': 'APP.DESCRIPTION.PROPOSE',
  'APP.SEO.SUMMARIZE.COMPANY_TEXT.FROM.WEBSITE': 'APP.SEO.SUMMARIZE.COMPANY_TEXT.FROM.WEBSITE',
  'APP.SEO.TEXT.OPTIMISE': 'APP.SEO.TEXT.OPTIMISE',
  'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.ELEMENT': 'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.ELEMENT',
  'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.HEADINGS': 'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.HEADINGS',
  'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.MAINCONTENT':
    'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.MAINCONTENT',
  'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS': 'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS',
  'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS.LEVEL': 'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS.LEVEL',
  'APP.ADS.GOOGLE.RESPONSIVE.SEARCH.ADS.VALIDATION': 'APP.ADS.GOOGLE.RESPONSIVE.SEARCH.ADS.VALIDATION',
  'APP.ADS.GOOGLE.ADS.TEXT.FORMAT': 'APP.ADS.GOOGLE.ADS.TEXT.FORMAT',
  'APP.ADS.GOOGLE.ADS.TEXTS.FORMAT': 'APP.ADS.GOOGLE.ADS.TEXTS.FORMAT',
  'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202':
    'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.INVOICE.VERIFICATION.CAEN_6202': 'APP.INTERNAL.CONTRACTORS.INVOICE.VERIFICATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.CONTRACT.VERIFICATION.CAEN_6202':
    'APP.INTERNAL.CONTRACTORS.CONTRACT.VERIFICATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.CONTRACT.EXTRACT.RELEVANT.PARTS':
    'APP.INTERNAL.CONTRACTORS.CONTRACT.EXTRACT.RELEVANT.PARTS',
  'APP.INTERNAL.CONTRACTORS.CONTRACT_EXTRACTION_FROM_PDF': 'APP.INTERNAL.CONTRACTORS.CONTRACT_EXTRACTION_FROM_PDF',
  'APP.INTERNAL.CONTRACTORS.VERIFICATION.CAEN_6202.SUMNMARY':
    'APP.INTERNAL.CONTRACTORS.VERIFICATION.CAEN_6202.SUMNMARY',
  'APP.INTERNAL.CONTRACTORS.CONTRACTS.VERIFICATION.CAEN_6202.SUMNMARY':
    'APP.INTERNAL.CONTRACTORS.CONTRACTS.VERIFICATION.CAEN_6202.SUMNMARY',
  'APP.INTERNAL.CONTRACTORS.INVOICES.VERIFICATION.CAEN_6202.SUMNMARY':
    'APP.INTERNAL.CONTRACTORS.INVOICES.VERIFICATION.CAEN_6202.SUMNMARY',
  'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202.ONBOARDING_CONSULTANT':
    'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202.ONBOARDING_CONSULTANT',
  'APP.INTERNAL.CONTRACTORS.INVOICE_EXTRACTION_FROM_PDF': 'APP.INTERNAL.CONTRACTORS.INVOICE_EXTRACTION_FROM_PDF',
  'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.EXTRACT': 'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.EXTRACT',
  'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202':
    'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202.SUMMARY':
    'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202.SUMMARY',
  'APP.AI.GENERATED.IMAGES': 'APP.AI.GENERATED.IMAGES',
  'APP.SEO.WEBPAGE.EXTRACT.MAINCONTENT': 'APP.SEO.WEBPAGE.EXTRACT.MAINCONTENT',
  'APP.SEO.WEBPAGE.EXTRACT.PAGE_STRUCTURE': 'APP.SEO.WEBPAGE.EXTRACT.PAGE_STRUCTURE',
};

export const AccountAICostPromptStrict = {
  'APP.TRANSLATIONS.MULTILOCALE.INFORMAL': 'APP.TRANSLATIONS.MULTILOCALE.INFORMAL',
  'APP.TRANSLATIONS.SINGLELOCALE.INFORMAL': 'APP.TRANSLATIONS.SINGLELOCALE.INFORMAL',
  'APP.TRANSLATIONS.SINGLELOCALE.FORMAL': 'APP.TRANSLATIONS.SINGLELOCALE.FORMAL',
  'APP.GENERATED.REVIEW.REPLY': 'APP.GENERATED.REVIEW.REPLY',
  'APP.GENERATED.REVIEW.REPLY.ADVANCED': 'APP.GENERATED.REVIEW.REPLY.ADVANCED',
  'APP.REPUTATION.REVIEWS.REPUTATION.TOPICS': 'APP.REPUTATION.REVIEWS.REPUTATION.TOPICS',
  'APP.REPUTATION.REVIEWS.REPUTATION.DIMENSIONS': 'APP.REPUTATION.REVIEWS.REPUTATION.DIMENSIONS',
  'APP.REPUTATION.SUMMARY': 'APP.REPUTATION.SUMMARY',
  'APP.GENERATED.POST.INSTRUCTION': 'APP.GENERATED.POST.INSTRUCTION',
  'APP.GENERATED.POST.COMPETITORS': 'APP.GENERATED.POST.COMPETITORS',
  'APP.GENERATED.COMMENT.REPLY': 'APP.GENERATED.COMMENT.REPLY',
  'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION': 'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION',
  'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION.ANALYSIS': 'APP.GENERATED.CAMPAIGN.POST.INSTRUCTION.ANALYSIS',
  'APP.AI.TEXT.KEYWORDS': 'APP.AI.TEXT.KEYWORDS',
  'APP.AI.PROMPT.INJECTION.DETECTION': 'APP.AI.PROMPT.INJECTION.DETECTION',
  'APP.AI.EMAIL_CONTENT.MODERATION': 'APP.AI.EMAIL_CONTENT.MODERATION',
  'APP.TRANSLATIONKEY.UNDERSTANDABILITY': 'APP.TRANSLATIONKEY.UNDERSTANDABILITY',
  'APP.AI.TEXT.ADJUST': 'APP.AI.TEXT.ADJUST',
  'APP.AI.TEXT.ADJUSTMENT': 'APP.AI.TEXT.ADJUSTMENT',
  'APP.GENERATED.EVENT.INSTRUCTION': 'APP.GENERATED.EVENT.INSTRUCTION',
  'APP.SEO.TEXT.OPTIMISATIONS': 'APP.SEO.TEXT.OPTIMISATIONS',
  'APP.SEO.TEXT.OPTIMISATION.LEVEL': 'APP.SEO.TEXT.OPTIMISATION.LEVEL',
  'APP.SEO.PROPOSE_KEYWORDS': 'APP.SEO.PROPOSE_KEYWORDS',
  'APP.SEO.PROPOSE_KEYWORDS.WEBSITE_CONTENT.ELEMENTS': 'APP.SEO.PROPOSE_KEYWORDS.WEBSITE_CONTENT.ELEMENTS',
  'APP.OPENING_HOURS.PROPOSE': 'APP.OPENING_HOURS.PROPOSE',
  'APP.DESCRIPTION.PROPOSE': 'APP.DESCRIPTION.PROPOSE',
  'APP.SEO.SUMMARIZE.COMPANY_TEXT.FROM.WEBSITE': 'APP.SEO.SUMMARIZE.COMPANY_TEXT.FROM.WEBSITE',
  'APP.SEO.TEXT.OPTIMISE': 'APP.SEO.TEXT.OPTIMISE',
  'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.ELEMENT': 'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.ELEMENT',
  'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.HEADINGS': 'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.HEADINGS',
  'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.MAINCONTENT':
    'APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.MAINCONTENT',
  'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS': 'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS',
  'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS.LEVEL': 'APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS.LEVEL',
  'APP.ADS.GOOGLE.RESPONSIVE.SEARCH.ADS.VALIDATION': 'APP.ADS.GOOGLE.RESPONSIVE.SEARCH.ADS.VALIDATION',
  'APP.ADS.GOOGLE.ADS.TEXT.FORMAT': 'APP.ADS.GOOGLE.ADS.TEXT.FORMAT',
  'APP.ADS.GOOGLE.ADS.TEXTS.FORMAT': 'APP.ADS.GOOGLE.ADS.TEXTS.FORMAT',
  'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202':
    'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.INVOICE.VERIFICATION.CAEN_6202': 'APP.INTERNAL.CONTRACTORS.INVOICE.VERIFICATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.CONTRACT.VERIFICATION.CAEN_6202':
    'APP.INTERNAL.CONTRACTORS.CONTRACT.VERIFICATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.CONTRACT.EXTRACT.RELEVANT.PARTS':
    'APP.INTERNAL.CONTRACTORS.CONTRACT.EXTRACT.RELEVANT.PARTS',
  'APP.INTERNAL.CONTRACTORS.CONTRACT_EXTRACTION_FROM_PDF': 'APP.INTERNAL.CONTRACTORS.CONTRACT_EXTRACTION_FROM_PDF',
  'APP.INTERNAL.CONTRACTORS.VERIFICATION.CAEN_6202.SUMNMARY':
    'APP.INTERNAL.CONTRACTORS.VERIFICATION.CAEN_6202.SUMNMARY',
  'APP.INTERNAL.CONTRACTORS.CONTRACTS.VERIFICATION.CAEN_6202.SUMNMARY':
    'APP.INTERNAL.CONTRACTORS.CONTRACTS.VERIFICATION.CAEN_6202.SUMNMARY',
  'APP.INTERNAL.CONTRACTORS.INVOICES.VERIFICATION.CAEN_6202.SUMNMARY':
    'APP.INTERNAL.CONTRACTORS.INVOICES.VERIFICATION.CAEN_6202.SUMNMARY',
  'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202.ONBOARDING_CONSULTANT':
    'APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202.ONBOARDING_CONSULTANT',
  'APP.INTERNAL.CONTRACTORS.INVOICE_EXTRACTION_FROM_PDF': 'APP.INTERNAL.CONTRACTORS.INVOICE_EXTRACTION_FROM_PDF',
  'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.EXTRACT': 'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.EXTRACT',
  'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202':
    'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202',
  'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202.SUMMARY':
    'APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202.SUMMARY',
  'APP.AI.GENERATED.IMAGES': 'APP.AI.GENERATED.IMAGES',
  'APP.SEO.WEBPAGE.EXTRACT.MAINCONTENT': 'APP.SEO.WEBPAGE.EXTRACT.MAINCONTENT',
  'APP.SEO.WEBPAGE.EXTRACT.PAGE_STRUCTURE': 'APP.SEO.WEBPAGE.EXTRACT.PAGE_STRUCTURE',
} as const;

export const AccountAICostInterval = {
  ALL_TIME: 'ALL_TIME',
  YEAR: 'YEAR',
  MONTH: 'MONTH',
  WEEK: 'WEEK',
  DATE: 'DATE',
};

export const AccountAICostIntervalStrict = {
  ALL_TIME: 'ALL_TIME',
  YEAR: 'YEAR',
  MONTH: 'MONTH',
  WEEK: 'WEEK',
  DATE: 'DATE',
} as const;

export const AccountAICostObjectType = {
  App_Domain_AI_Entities_Models_Accounts_AICosts_AccountAICost:
    'App\\Domain\\AI\\Entities\\Models\\Accounts\\AICosts\\AccountAICost',
};

export const AccountAICostObjectTypeStrict = {
  App_Domain_AI_Entities_Models_Accounts_AICosts_AccountAICost:
    'App\\Domain\\AI\\Entities\\Models\\Accounts\\AICosts\\AccountAICost',
} as const;

export type AccountAICost = {
  /**
   * The prompt for which costs have been spent
   *  Allowed Values:
   * -   `APP.TRANSLATIONS.MULTILOCALE.INFORMAL`
   * -   `APP.TRANSLATIONS.SINGLELOCALE.INFORMAL`
   * -   `APP.TRANSLATIONS.SINGLELOCALE.FORMAL`
   * -   `APP.GENERATED.REVIEW.REPLY`
   * -   `APP.GENERATED.REVIEW.REPLY.ADVANCED`
   * -   `APP.REPUTATION.REVIEWS.REPUTATION.TOPICS`
   * -   `APP.REPUTATION.REVIEWS.REPUTATION.DIMENSIONS`
   * -   `APP.REPUTATION.SUMMARY`
   * -   `APP.GENERATED.POST.INSTRUCTION`
   * -   `APP.GENERATED.POST.COMPETITORS`
   * -   `APP.GENERATED.COMMENT.REPLY`
   * -   `APP.GENERATED.CAMPAIGN.POST.INSTRUCTION`
   * -   `APP.GENERATED.CAMPAIGN.POST.INSTRUCTION.ANALYSIS`
   * -   `APP.AI.TEXT.KEYWORDS`
   * -   `APP.AI.PROMPT.INJECTION.DETECTION`
   * -   `APP.AI.EMAIL_CONTENT.MODERATION`
   * -   `APP.TRANSLATIONKEY.UNDERSTANDABILITY`
   * -   `APP.AI.TEXT.ADJUST`
   * -   `APP.AI.TEXT.ADJUSTMENT`
   * -   `APP.GENERATED.EVENT.INSTRUCTION`
   * -   `APP.SEO.TEXT.OPTIMISATIONS`
   * -   `APP.SEO.TEXT.OPTIMISATION.LEVEL`
   * -   `APP.SEO.PROPOSE_KEYWORDS`
   * -   `APP.SEO.PROPOSE_KEYWORDS.WEBSITE_CONTENT.ELEMENTS`
   * -   `APP.OPENING_HOURS.PROPOSE`
   * -   `APP.DESCRIPTION.PROPOSE`
   * -   `APP.SEO.SUMMARIZE.COMPANY_TEXT.FROM.WEBSITE`
   * -   `APP.SEO.TEXT.OPTIMISE`
   * -   `APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.ELEMENT`
   * -   `APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.HEADINGS`
   * -   `APP.SEO.GENERATE.OR.OPTIMIZE.WEBPAGE.CONTENT.MAINCONTENT`
   * -   `APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS`
   * -   `APP.SEO.CONTENT.ELEMENTS.OPTIMISATIONS.LEVEL`
   * -   `APP.ADS.GOOGLE.RESPONSIVE.SEARCH.ADS.VALIDATION`
   * -   `APP.ADS.GOOGLE.ADS.TEXT.FORMAT`
   * -   `APP.ADS.GOOGLE.ADS.TEXTS.FORMAT`
   * -   `APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202`
   * -   `APP.INTERNAL.CONTRACTORS.INVOICE.VERIFICATION.CAEN_6202`
   * -   `APP.INTERNAL.CONTRACTORS.CONTRACT.VERIFICATION.CAEN_6202`
   * -   `APP.INTERNAL.CONTRACTORS.CONTRACT.EXTRACT.RELEVANT.PARTS`
   * -   `APP.INTERNAL.CONTRACTORS.CONTRACT_EXTRACTION_FROM_PDF`
   * -   `APP.INTERNAL.CONTRACTORS.VERIFICATION.CAEN_6202.SUMNMARY`
   * -   `APP.INTERNAL.CONTRACTORS.CONTRACTS.VERIFICATION.CAEN_6202.SUMNMARY`
   * -   `APP.INTERNAL.CONTRACTORS.INVOICES.VERIFICATION.CAEN_6202.SUMNMARY`
   * -   `APP.INTERNAL.CONTRACTORS.INVOICE_DOCUMENTATION.CAEN_6202.ONBOARDING_CONSULTANT`
   * -   `APP.INTERNAL.CONTRACTORS.INVOICE_EXTRACTION_FROM_PDF`
   * -   `APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.EXTRACT`
   * -   `APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202`
   * -   `APP.INTERNAL.CONTRACTORS.SOCIAL_MEDIA.LINKEDIN.PROFESSIONAL_EXPERIENCE.VERIFICATION.CAEN_6202.SUMMARY`
   * -   `APP.AI.GENERATED.IMAGES`
   * -   `APP.SEO.WEBPAGE.EXTRACT.MAINCONTENT`
   * -   `APP.SEO.WEBPAGE.EXTRACT.PAGE_STRUCTURE`
   *
   */
  prompt?: (typeof AccountAICostPrompt)[keyof typeof AccountAICostPrompt];
  /**
   * The summarizing interval of the AI Service Cost e.g. YEAR, WEEK etc.
   *  Allowed Values:
   * -   `ALL_TIME`: The All-Time Interval for AI Costs
   * -   `YEAR`: The Yearly Interval for AI Costs
   * -   `MONTH`: The Monthly Interval for AI Costs
   * -   `WEEK`: The Weekly Interval for AI Costs
   * -   `DATE`: The Date Interval for AI Costs
   *
   */
  interval?: (typeof AccountAICostInterval)[keyof typeof AccountAICostInterval];
  /**
   * The first date of the interval e.g.
   * - in case of type ALL_TIME: null, no date necessary
   * - in case of type YEAR: <year>-01-01
   * - in case of type MONTH: <year>-<month>-01
   * - in case of type WEEK: first day of week (monday) of all tracks logged in the particular week, e.g. 2023-01-02
   * - in case of type DATE: the exact date yyyy-mm-dd
   */
  firstDateOfInterval?: string;
  /**
   * Account ID
   */
  accountId?: number;
  account?: Account;
  /**
   * Project ID
   */
  projectId?: number;
  project?: Project;
  /**
   * Total Costs for the AI service in the interval
   */
  costsInUSD?: number;
  /**
   * Number of usages of the AI service in the interval
   */
  usageCount?: number;
  /**
   * The fully qualified class name of the object
   */
  objectType: (typeof AccountAICostObjectType)[keyof typeof AccountAICostObjectType];
  /**
   * The internal identifier of the entity
   */
  id?: number;
  changeHistory?: ChangeHistory;
};
