export const Validations = {
  CONFIG_COMPANY_NAME_MIN_LENGTH: 3,
  CONFIG_COMPANY_NAME_MAX_LENGTH: 128,
  CONFIG_SHORT_DESCRIPTION_MAX_LENGTH: 100,
  CONFIG_DETAILED_DESCRIPTION_MAX_LENGTH: 750,
  CONFIG_REVIEWS_REPLY_MAX_LENGTH: 4000,
  CONFIG_MAX_CATEGORIES: 10,
  CONFIG_DESCRIPTION_SHORT_MAX_LENGTH: 200,
  CONFIG_DESCRIPTION_LONG_MAX_LENGTH: 750,
  CONFIG_BUSINESS_EMAIL_LONG_MAX: 196,
  CONFIG_CONTACT_EMAIL_LONG_MAX: 80,
};
