import { Ddd_Localmarketing_Domain_Dtos_Categories_Category } from '@models/swagger//Ddd_Localmarketing_Domain_Dtos_Categories_Category';
import { Ddd_Localmarketing_Domain_Dtos_Photos_Photo_Response } from '@models/swagger//Ddd_Localmarketing_Domain_Dtos_Photos_Photo_Response';
import { Ddd_Localmarketing_Domain_Dtos_Profilepage_Address_Response } from '@models/swagger//Ddd_Localmarketing_Domain_Dtos_Profilepage_Address_Response';
import { Ddd_Localmarketing_Domain_Dtos_Profilepage_Openinghours_Object } from '@models/swagger//Ddd_Localmarketing_Domain_Dtos_Profilepage_Openinghours_Object';

export type Ddd_Localmarketing_Domain_Dtos_Profilepage_Response = {
  companyName?: string;
  categories?: Ddd_Localmarketing_Domain_Dtos_Categories_Category[];
  sitePrimaryCategoryName?: string;
  additionalCategories?: string[];
  phone?: string;
  mobilePhone?: string;
  additionalPhone?: string;
  fax?: string;
  domain?: string;
  email?: string;
  detailedDescription?: string;
  shortDescription?: string;
  usesShortDescription?: boolean;
  logo?: Ddd_Localmarketing_Domain_Dtos_Photos_Photo_Response;
  cover?: Ddd_Localmarketing_Domain_Dtos_Photos_Photo_Response;
  gallery?: Ddd_Localmarketing_Domain_Dtos_Photos_Photo_Response[];
  gmbGallery?: Ddd_Localmarketing_Domain_Dtos_Photos_Photo_Response[];
  openingHours?: Ddd_Localmarketing_Domain_Dtos_Profilepage_Openinghours_Object;
  address?: Ddd_Localmarketing_Domain_Dtos_Profilepage_Address_Response;
  keywords?: string[];
  errors?: string[];
  googleGeoCode?: string;
  $countryId?: number;
  city?: string;
  googleValidatedAddress?: string;
  street?: string;
  streetno?: string;
  postalcode?: string;
  address_first_line?: string;
  address_second_line?: string;
  lat?: string;
  lng?: string;
  language?: string;
};
