export type GaAccountPromoDataSchema = {
  monthlyPricePerMonth?: string;
  monthlyPricePerYear?: string;
  yearlyPricePerMonth?: string;
  yearlyPricePerYear?: string;
  monthlyPromocodeValid?: boolean;
  yearlyPromocodeValid?: boolean;
  monthlyPricePerMonthWithPromocode?: string;
  yearlyPricePerMonthWithPromocode?: string;
  yearlyPricePerYearWithPromocode?: string;
  savePercent?: number;
  upgradePeroidToggler?: boolean;
  userTotalBudget?: number;
  userCurrency?: string;
  isVatPayer?: boolean;
  userDomain?: string;
  totalWithCurrency?: string;
  campaignBudget?: number;
  adKeyword?: string;
  adTitle?: string;
  monthly360?: number;
  annual360?: number;
  countryIsEUMember?: boolean;
  setupFee?: string;
  shouldAddSetupFee?: boolean;
};
