export type NewData = {
  created_time?: number;
  tweet_id?: string;
  text?: string;
  user_id?: number;
  name?: string;
  user_name?: string;
  user_location?: string;
  user_description?: string;
  user_profile_image?: string;
  link?: string;
  media_id?: number;
  full_picture?: string;
  type?: string;
  description?: string;
  post_id?: string;
  shared?: null;
  city_name?: string;
  country_name?: null;
  position?: string;
  created_date?: string;
  media_link?: string;
  retweet_created_time?: string;
  retweet_text?: string;
};
