import { UpsellingSubscriptionCustomUpsellingLinkParams } from '@models/swagger//UpsellingSubscriptionCustomUpsellingLinkParams';
import { UpsellingSubscriptionFeaturesDataSchema } from '@models/swagger//UpsellingSubscriptionFeaturesDataSchema';
import { UpsellingSubscriptionFeaturesSchema } from '@models/swagger//UpsellingSubscriptionFeaturesSchema';
import { UpsellingSubscriptionSpecialOffers } from '@models/swagger//UpsellingSubscriptionSpecialOffers';

export type UpsellingSubscriptionSchema = {
  id?: number;
  featureRecurringSum?: number;
  priceMonthly?: number;
  priceYearly?: number;
  cancellationDuration?: number;
  oneTimeSetup?: number;
  isActive?: boolean;
  hasPromotion?: boolean;
  billingPeriod?: string;
  featuresData?: UpsellingSubscriptionFeaturesSchema[];
  featuresToUpgrade?: UpsellingSubscriptionFeaturesDataSchema[];
  productName?: string;
  mainName?: string;
  productGroup?: string;
  fakeDiscountPercentage?: string;
  price?: number;
  oldPrice?: number;
  oldPriceYearly?: number;
  customUpsellingLink?: string;
  customUpsellingLinkParams?: UpsellingSubscriptionCustomUpsellingLinkParams;
  subcriptionBlackFridayDataMonthly?: UpsellingSubscriptionSpecialOffers;
  subcriptionBlackFridayDataYearly?: UpsellingSubscriptionSpecialOffers;
  isFreeTrialMonthly?: boolean;
  isFreeTrialYearly?: boolean;
  customBadgeTextMonthly?: string;
  customBadgeTextYearly?: string;
};
