import { CompanyData } from '@models/swagger//CompanyData';
import { Entities } from '@models/swagger//Entities';
import { ExtraData } from '@models/swagger//ExtraData';
import { LastData } from '@models/swagger//LastData';
import { NewData } from '@models/swagger//NewData';
import { Upsellings } from '@models/swagger//Upsellings';

export type VisionFeedResponseItem = {
  data_created_time?: number;
  data_id?: string;
  data_text?: string;
  data_media_id?: string;
  data_full_picture?: string;
  data_link?: string;
  data_type?: string;
  data_user_id?: number;
  data_name?: string;
  data_user_name?: string;
  data_user_location?: string;
  data_user_description?: string;
  data_user_profile_image?: string;
  data_user_verified?: string;
  data_descrption?: string;
  entities?: Entities;
  entity?: string;
  last_data?: LastData;
  new_data?: NewData;
  extra_data?: ExtraData;
  changed_fields?: string[];
  group_id?: string;
  message?: null;
  id?: string;
  type?: string;
  source?: string;
  created_time?: number;
  notification_time?: number;
  notification_id?: string;
  is_competitor?: boolean;
  company_data?: CompanyData;
  upsellings?: Upsellings;
  score?: number;
  company_id?: string;
  created_date?: string;
  order_id?: string;
  created_day?: string;
  hash?: string;
  form?: string;
  data_city_name?: string;
  data_country_name?: string;
  data_position?: string;
};
