import { GoogleAnalyticsPropertyTrafficAcquisitionCategoryReport } from '@models/swagger/App/Domain/Seo/Repo/Argus/Locations/Seo/Analytics/Reports/PropertyReportResponse/GoogleAnalyticsPropertyAcquisitionReports/GoogleAnalyticsPropertyTrafficAcquisitionReport/GoogleAnalyticsPropertyTrafficAcquisitionCategoryReport';

export const GoogleAnalyticsPropertyTrafficAcquisitionReportObjectType = {
  App_Domain_Seo_Repo_Argus_Locations_Seo_Analytics_Reports_PropertyReportResponse_GoogleAnalyticsPropertyAcquisitionReports_GoogleAnalyticsPropertyTrafficAcquisitionReport_GoogleAnalyticsPropertyTrafficAcquisitionReport:
    'App\\Domain\\Seo\\Repo\\Argus\\Locations\\Seo\\Analytics\\Reports\\PropertyReportResponse\\GoogleAnalyticsPropertyAcquisitionReports\\GoogleAnalyticsPropertyTrafficAcquisitionReport\\GoogleAnalyticsPropertyTrafficAcquisitionReport',
};

export const GoogleAnalyticsPropertyTrafficAcquisitionReportObjectTypeStrict = {
  App_Domain_Seo_Repo_Argus_Locations_Seo_Analytics_Reports_PropertyReportResponse_GoogleAnalyticsPropertyAcquisitionReports_GoogleAnalyticsPropertyTrafficAcquisitionReport_GoogleAnalyticsPropertyTrafficAcquisitionReport:
    'App\\Domain\\Seo\\Repo\\Argus\\Locations\\Seo\\Analytics\\Reports\\PropertyReportResponse\\GoogleAnalyticsPropertyAcquisitionReports\\GoogleAnalyticsPropertyTrafficAcquisitionReport\\GoogleAnalyticsPropertyTrafficAcquisitionReport',
} as const;

export type GoogleAnalyticsPropertyTrafficAcquisitionReport = {
  sessionDefaultChannelGroup?: GoogleAnalyticsPropertyTrafficAcquisitionCategoryReport;
  sessionMedium?: GoogleAnalyticsPropertyTrafficAcquisitionCategoryReport;
  sessionSource?: GoogleAnalyticsPropertyTrafficAcquisitionCategoryReport;
  sessionSourceMedium?: GoogleAnalyticsPropertyTrafficAcquisitionCategoryReport;
  sessionSourcePlatform?: GoogleAnalyticsPropertyTrafficAcquisitionCategoryReport;
  /**
   * The fully qualified class name of the object
   */
  objectType: (typeof GoogleAnalyticsPropertyTrafficAcquisitionReportObjectType)[keyof typeof GoogleAnalyticsPropertyTrafficAcquisitionReportObjectType];
};
