import { AdsGoogleCampaignBudgetFeatureFlagSetting } from '@models/swagger/App/Domain/Ads/Entities/FeatureFlags/AdsGoogleCampaignBudgetFeatureFlagSetting';
import { MetaBoostCampaignBudgetFeatureFlagSetting } from '@models/swagger/App/Domain/Ads/Entities/FeatureFlags/MetaBoostCampaignBudgetFeatureFlagSetting';
import { AIBudgetFeatureFlagSetting } from '@models/swagger/App/Domain/AI/Entities/FeatureFlags/AIBudgetFeatureFlagSetting';
import { ListingServiceFeatureFlagSetting } from '@models/swagger/App/Domain/Presence/Entities/FeatureFlags/ListingServiceFeatureFlagSetting';
import { FacebookFeatureFlagSetting } from '@models/swagger/App/Domain/Presence/Entities/ListingServices/Facebook/FeatureFlags/FacebookFeatureFlagSetting';
import { GoogleFeatureFlagSetting } from '@models/swagger/App/Domain/Presence/Entities/ListingServices/Google/FeatureFlags/GoogleFeatureFlagSetting';
import { LinkedInFeatureFlagSetting } from '@models/swagger/App/Domain/Presence/Entities/ListingServices/Linkedin/FeatureFlags/LinkedInFeatureFlagSetting';
import { UberallFeatureFlagSetting } from '@models/swagger/App/Domain/Presence/Entities/ListingServices/Uberall/FeatureFlags/UberallFeatureFlagSetting';
import { XFeatureFlagSetting } from '@models/swagger/App/Domain/Presence/Entities/ListingServices/X/FeatureFlags/XFeatureFlagSetting';
import { YextFeatureFlagSetting } from '@models/swagger/App/Domain/Presence/Entities/ListingServices/Yext/FeatureFlags/YextFeatureFlagSetting';
import { AppliedFeatureFlagUpgrades } from '@models/swagger/App/Domain/Product/Entities/Products/FeatureFlags/AppliedFeatureFlagUpgrades';
import { RadarFeedFeatureFlagSetting } from '@models/swagger/App/Domain/Radar/Entities/FeatureFlags/RadarFeedFeatureFlagSetting';
import { SeoRankingsFeatureFlagSetting } from '@models/swagger/App/Domain/Seo/Entities/FeatureFlags/SeoRankingsFeatureFlagSetting';
import { SetupCommonCompetitorsFeatureFlagSetting } from '@models/swagger/App/Domain/Setup/Entities/FeatureFlags/SetupCommonCompetitorsFeatureFlagSetting';
import { SetupCommonFeatureFlagSetting } from '@models/swagger/App/Domain/Setup/Entities/FeatureFlags/SetupCommonFeatureFlagSetting';
import { SetupCommonKeywordsFeatureFlagSetting } from '@models/swagger/App/Domain/Setup/Entities/FeatureFlags/SetupCommonKeywordsFeatureFlagSetting';
import { SetupCommonLocationsFeatureFlagSetting } from '@models/swagger/App/Domain/Setup/Entities/FeatureFlags/SetupCommonLocationsFeatureFlagSetting';

export const AppliedFeatureFlagName = {
  'COMMON.SIDENAV': 'COMMON.SIDENAV',
  'COMMON.SIDENAV.OVERVIEW': 'COMMON.SIDENAV.OVERVIEW',
  'COMMON.SIDENAV.SEO': 'COMMON.SIDENAV.SEO',
  'COMMON.SIDENAV.SEO.DASHBOARD': 'COMMON.SIDENAV.SEO.DASHBOARD',
  'COMMON.SIDENAV.SEO.TASKS': 'COMMON.SIDENAV.SEO.TASKS',
  'COMMON.SIDENAV.SEO.INSIGHTS': 'COMMON.SIDENAV.SEO.INSIGHTS',
  'COMMON.SIDENAV.PRESENCE': 'COMMON.SIDENAV.PRESENCE',
  'COMMON.SIDENAV.PRESENCE.DSHBOARD': 'COMMON.SIDENAV.PRESENCE.DSHBOARD',
  'COMMON.SIDENAV.PRESENCE.PROFILE': 'COMMON.SIDENAV.PRESENCE.PROFILE',
  'COMMON.SIDENAV.PRESENCE.PROFILEFINETUNING': 'COMMON.SIDENAV.PRESENCE.PROFILEFINETUNING',
  'COMMON.SIDENAV.PRESENCE.LISTINGS': 'COMMON.SIDENAV.PRESENCE.LISTINGS',
  'COMMON.SIDENAV.PRESENCE.INSIGHTS': 'COMMON.SIDENAV.PRESENCE.INSIGHTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.DASHBOARD': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.DASHBOARD',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.CHAT': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.CHAT',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.POSTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.POSTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.EVENTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.EVENTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.OFFERS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.OFFERS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PRODUCTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PRODUCTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.BOOSTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.BOOSTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PLANNER': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PLANNER',
  'COMMON.SIDENAV.REPUTATION': 'COMMON.SIDENAV.REPUTATION',
  'COMMON.SIDENAV.REPUTATION.REVIEWS': 'COMMON.SIDENAV.REPUTATION.REVIEWS',
  'COMMON.SIDENAV.REPUTATION.REPLYTEMPLATES': 'COMMON.SIDENAV.REPUTATION.REPLYTEMPLATES',
  'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER': 'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER',
  'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.CUSTOMERS': 'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.CUSTOMERS',
  'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.PRINT': 'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.PRINT',
  'COMMON.SIDENAV.REPUTATION.INSIGHTS': 'COMMON.SIDENAV.REPUTATION.INSIGHTS',
  'COMMON.SIDENAV.REPUTATION.WIDGETS.REPUTATIONWIDGET': 'COMMON.SIDENAV.REPUTATION.WIDGETS.REPUTATIONWIDGET',
  'COMMON.SIDENAV.REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET':
    'COMMON.SIDENAV.REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET',
  'COMMON.SIDENAV.REPUTATION.REVIEWSOURCES': 'COMMON.SIDENAV.REPUTATION.REVIEWSOURCES',
  'COMMON.SIDENAV.REPUTATION.MENTIONS': 'COMMON.SIDENAV.REPUTATION.MENTIONS',
  'COMMON.SIDENAV.ADS': 'COMMON.SIDENAV.ADS',
  'COMMON.SIDENAV.ADS.DASHBOARD': 'COMMON.SIDENAV.ADS.DASHBOARD',
  'COMMON.SIDENAV.ADS.BUDGET': 'COMMON.SIDENAV.ADS.BUDGET',
  'COMMON.SIDENAV.ADS.GOOGLE': 'COMMON.SIDENAV.ADS.GOOGLE',
  'COMMON.SIDENAV.ADS.SOCIAL': 'COMMON.SIDENAV.ADS.SOCIAL',
  'COMMON.SIDENAV.SETTINGS': 'COMMON.SIDENAV.SETTINGS',
  'COMMON.SIDENAV.BLOG': 'COMMON.SIDENAV.BLOG',
  'COMMON.TOPNAV': 'COMMON.TOPNAV',
  'COMMON.TOPNAV.MANAGEPROJECTS': 'COMMON.TOPNAV.MANAGEPROJECTS',
  'COMMON.TOPNAV.ACCOUNT': 'COMMON.TOPNAV.ACCOUNT',
  'COMMON.TOPNAV.JUMPSTART': 'COMMON.TOPNAV.JUMPSTART',
  'COMMON.JUMPSTART': 'COMMON.JUMPSTART',
  'COMMON.SUPPORT': 'COMMON.SUPPORT',
  'COMMON.SUPPORT.PREMIUM': 'COMMON.SUPPORT.PREMIUM',
  'AI.BUDGET': 'AI.BUDGET',
  'SEO.RANKINGS': 'SEO.RANKINGS',
  'SEO.RANKINGS.MAPS': 'SEO.RANKINGS.MAPS',
  'SEO.INSIGHTS.LVI': 'SEO.INSIGHTS.LVI',
  'SEO.INSIGHTS.RANKINGS.SEARCH': 'SEO.INSIGHTS.RANKINGS.SEARCH',
  'SEO.INSIGHTS.RANKINGS.MAPS': 'SEO.INSIGHTS.RANKINGS.MAPS',
  'SEO.INSIGHTS.RANKINGS.KEYWORD_DETAILS': 'SEO.INSIGHTS.RANKINGS.KEYWORD_DETAILS',
  'SEO.INSIGHTS.RANKINGS.COMPETITORS': 'SEO.INSIGHTS.RANKINGS.COMPETITORS',
  'SEO.TASKS': 'SEO.TASKS',
  'RADAR.FEED': 'RADAR.FEED',
  'ADS.GOOGLE.CAMPAIGN.CREATE': 'ADS.GOOGLE.CAMPAIGN.CREATE',
  'ADS.GOOGLE.CAMPAIGN.BUDGET': 'ADS.GOOGLE.CAMPAIGN.BUDGET',
  'ADS.GOOGLE.CAMPAIGN.LAUNCH': 'ADS.GOOGLE.CAMPAIGN.LAUNCH',
  'PRESENCE.LVI': 'PRESENCE.LVI',
  'PRESENCE.DSHBOARD.NBA': 'PRESENCE.DSHBOARD.NBA',
  'PRESENCE.DSHBOARD.LVI': 'PRESENCE.DSHBOARD.LVI',
  'PRESENCE.DSHBOARD.TOPRANKINGS.SEARCH': 'PRESENCE.DSHBOARD.TOPRANKINGS.SEARCH',
  'PRESENCE.DSHBOARD.TOPRANKINGS.MAPS': 'PRESENCE.DSHBOARD.TOPRANKINGS.MAPS',
  'PRESENCE.DSHBOARD.COMPETITORSMAP': 'PRESENCE.DSHBOARD.COMPETITORSMAP',
  'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING': 'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING',
  'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING.LISTINGSCHECKER': 'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING.LISTINGSCHECKER',
  'PRESENCE.DSHBOARD.ENGAGEMENT': 'PRESENCE.DSHBOARD.ENGAGEMENT',
  'PRESENCE.DSHBOARD.ENGAGEMENT.PLANNER': 'PRESENCE.DSHBOARD.ENGAGEMENT.PLANNER',
  'PRESENCE.PROFILE.DETAILS': 'PRESENCE.PROFILE.DETAILS',
  'PRESENCE.PROFILE.ADDRESS': 'PRESENCE.PROFILE.ADDRESS',
  'PRESENCE.PROFILE.OPENINGHOURS': 'PRESENCE.PROFILE.OPENINGHOURS',
  'PRESENCE.PROFILE.CATEGORIES': 'PRESENCE.PROFILE.CATEGORIES',
  'PRESENCE.PROFILE.DESCRIPTION': 'PRESENCE.PROFILE.DESCRIPTION',
  'PRESENCE.PROFILE.MEDIAITEMS': 'PRESENCE.PROFILE.MEDIAITEMS',
  'PRESENCE.PROFILEFINETUNING.SERVICEITEMS': 'PRESENCE.PROFILEFINETUNING.SERVICEITEMS',
  'PRESENCE.PROFILEFINETUNING.ATTRIBUTES': 'PRESENCE.PROFILEFINETUNING.ATTRIBUTES',
  'PRESENCE.LISTINGS.LISTINGSERVICES': 'PRESENCE.LISTINGS.LISTINGSERVICES',
  'PRESENCE.LISTINGS.LISTINGSERVICES.GOOGLE': 'PRESENCE.LISTINGS.LISTINGSERVICES.GOOGLE',
  'PRESENCE.LISTINGS.LISTINGSERVICES.FACEBOOK': 'PRESENCE.LISTINGS.LISTINGSERVICES.FACEBOOK',
  'PRESENCE.LISTINGS.LISTINGSERVICES.INSTAGRAM': 'PRESENCE.LISTINGS.LISTINGSERVICES.INSTAGRAM',
  'PRESENCE.LISTINGS.LISTINGSERVICES.UBERALL': 'PRESENCE.LISTINGS.LISTINGSERVICES.UBERALL',
  'PRESENCE.LISTINGS.LISTINGSERVICES.YEXT': 'PRESENCE.LISTINGS.LISTINGSERVICES.YEXT',
  'PRESENCE.LISTINGS.LISTINGSERVICES.LINKEDIN': 'PRESENCE.LISTINGS.LISTINGSERVICES.LINKEDIN',
  'PRESENCE.LISTINGS.LISTINGSERVICES.X': 'PRESENCE.LISTINGS.LISTINGSERVICES.X',
  'PRESENCE.LISTINGS.LISTINGSCHECKER': 'PRESENCE.LISTINGS.LISTINGSCHECKER',
  'PRESENCE.ENGAGEMENT.CHAT': 'PRESENCE.ENGAGEMENT.CHAT',
  'PRESENCE.ENGAGEMENT.EVENTS': 'PRESENCE.ENGAGEMENT.EVENTS',
  'PRESENCE.ENGAGEMENT.EVENTS.AI': 'PRESENCE.ENGAGEMENT.EVENTS.AI',
  'PRESENCE.ENGAGEMENT.POSTS': 'PRESENCE.ENGAGEMENT.POSTS',
  'PRESENCE.ENGAGEMENT.POSTS.AI': 'PRESENCE.ENGAGEMENT.POSTS.AI',
  'PRESENCE.ENGAGEMENT.POSTS.AI.COMPETITORS': 'PRESENCE.ENGAGEMENT.POSTS.AI.COMPETITORS',
  'PRESENCE.ENGAGEMENT.POSTS.SCHEDULING': 'PRESENCE.ENGAGEMENT.POSTS.SCHEDULING',
  'PRESENCE.ENGAGEMENT.BOOSTS': 'PRESENCE.ENGAGEMENT.BOOSTS',
  'PRESENCE.ENGAGEMENT.BOOSTS.BUDGET': 'PRESENCE.ENGAGEMENT.BOOSTS.BUDGET',
  'PRESENCE.ENGAGEMENT.PLANNER': 'PRESENCE.ENGAGEMENT.PLANNER',
  'PRESENCE.ENGAGEMENT.PLANNER.ADVANCEDSCHEDULING': 'PRESENCE.ENGAGEMENT.PLANNER.ADVANCEDSCHEDULING',
  'PRESENCE.ENGAGEMENT.POSTS.AI.IMAGES': 'PRESENCE.ENGAGEMENT.POSTS.AI.IMAGES',
  'PRESENCE.INSIGHTS.LVI': 'PRESENCE.INSIGHTS.LVI',
  'PRESENCE.INSIGHTS.TOPRANKINGS.SEARCH': 'PRESENCE.INSIGHTS.TOPRANKINGS.SEARCH',
  'PRESENCE.INSIGHTS.TOPRANKINGS.MAPS': 'PRESENCE.INSIGHTS.TOPRANKINGS.MAPS',
  'PRESENCE.INSIGHTS.COMPETITORSMAP': 'PRESENCE.INSIGHTS.COMPETITORSMAP',
  'PRESENCE.INSIGHTS.GOOGLE': 'PRESENCE.INSIGHTS.GOOGLE',
  'PRESENCE.INSIGHTS.GOOGLE.INTERACTIONS': 'PRESENCE.INSIGHTS.GOOGLE.INTERACTIONS',
  'PRESENCE.INSIGHTS.GOOGLE.VIEWS': 'PRESENCE.INSIGHTS.GOOGLE.VIEWS',
  'PRESENCE.INSIGHTS.GOOGLE.PLATFORMS': 'PRESENCE.INSIGHTS.GOOGLE.PLATFORMS',
  'PRESENCE.INSIGHTS.GOOGLE.MEDIAITEM': 'PRESENCE.INSIGHTS.GOOGLE.MEDIAITEM',
  'PRESENCE.INSIGHTS.RANKINGS.SEARCH': 'PRESENCE.INSIGHTS.RANKINGS.SEARCH',
  'PRESENCE.INSIGHTS.RANKINGS.MAPS': 'PRESENCE.INSIGHTS.RANKINGS.MAPS',
  'REPUTATION.DSHBOARD.NBA': 'REPUTATION.DSHBOARD.NBA',
  'REPUTATION.DSHBOARD.SUMMARY': 'REPUTATION.DSHBOARD.SUMMARY',
  'REPUTATION.DSHBOARD.CLUSTERS': 'REPUTATION.DSHBOARD.CLUSTERS',
  'REPUTATION.DSHBOARD.CLUSTERS.GRADIENTCHART': 'REPUTATION.DSHBOARD.CLUSTERS.GRADIENTCHART',
  'REPUTATION.DSHBOARD.CLUSTERS.STARAVERAGE': 'REPUTATION.DSHBOARD.CLUSTERS.STARAVERAGE',
  'REPUTATION.DSHBOARD.CLUSTERS.REVIEWVOLUME': 'REPUTATION.DSHBOARD.CLUSTERS.REVIEWVOLUME',
  'REPUTATION.DSHBOARD.CLUSTERS.REVIEWRECENCY': 'REPUTATION.DSHBOARD.CLUSTERS.REVIEWRECENCY',
  'REPUTATION.DSHBOARD.CLUSTERS.REVIEWLENGTH': 'REPUTATION.DSHBOARD.CLUSTERS.REVIEWLENGTH',
  'REPUTATION.DSHBOARD.CLUSTERS.REPLYRATE': 'REPUTATION.DSHBOARD.CLUSTERS.REPLYRATE',
  'REPUTATION.DSHBOARD.REVIEWSTATUS': 'REPUTATION.DSHBOARD.REVIEWSTATUS',
  'REPUTATION.DSHBOARD.RATINGSANDREVIEWS': 'REPUTATION.DSHBOARD.RATINGSANDREVIEWS',
  'REPUTATION.DSHBOARD.REVIEWSOURCES': 'REPUTATION.DSHBOARD.REVIEWSOURCES',
  'REPUTATION.REVIEWS': 'REPUTATION.REVIEWS',
  'REPUTATION.REVIEWS.REPLY': 'REPUTATION.REVIEWS.REPLY',
  'REPUTATION.REVIEWS.YEXT.REPLY': 'REPUTATION.REVIEWS.YEXT.REPLY',
  'REPUTATION.REVIEWS.REPLY.AI': 'REPUTATION.REVIEWS.REPLY.AI',
  'REPUTATION.REPLYTEMPLATES.AI': 'REPUTATION.REPLYTEMPLATES.AI',
  'REPUTATION.REVIEWBOOSTER': 'REPUTATION.REVIEWBOOSTER',
  'REPUTATION.REVIEWBOOSTER.MAIL': 'REPUTATION.REVIEWBOOSTER.MAIL',
  'REPUTATION.REVIEWBOOSTER.SMS': 'REPUTATION.REVIEWBOOSTER.SMS',
  'REPUTATION.REVIEWBOOSTER.AI': 'REPUTATION.REVIEWBOOSTER.AI',
  'REPUTATION.REVIEWBOOSTER.PRINT': 'REPUTATION.REVIEWBOOSTER.PRINT',
  'REPUTATION.REVIEWSOURCES': 'REPUTATION.REVIEWSOURCES',
  'REPUTATION.MENTIONS': 'REPUTATION.MENTIONS',
  'REPUTATION.INSIGHTS.SUMMARY': 'REPUTATION.INSIGHTS.SUMMARY',
  'REPUTATION.CINSIGHTS.CLUSTERS': 'REPUTATION.CINSIGHTS.CLUSTERS',
  'REPUTATION.INSIGHTS.CLUSTERS.GRADIENTCHART': 'REPUTATION.INSIGHTS.CLUSTERS.GRADIENTCHART',
  'REPUTATION.INSIGHTS.CLUSTERS.STARAVERAGE': 'REPUTATION.INSIGHTS.CLUSTERS.STARAVERAGE',
  'REPUTATION.INSIGHTS.CLUSTERS.REVIEWVOLUME': 'REPUTATION.INSIGHTS.CLUSTERS.REVIEWVOLUME',
  'REPUTATION.INSIGHTS.CLUSTERS.REVIEWRECENCY': 'REPUTATION.INSIGHTS.CLUSTERS.REVIEWRECENCY',
  'REPUTATION.INSIGHTS.CLUSTERS.REVIEWLENGTH': 'REPUTATION.INSIGHTS.CLUSTERS.REVIEWLENGTH',
  'REPUTATION.INSIGHTS.CLUSTERS.REPLYRATE': 'REPUTATION.INSIGHTS.CLUSTERS.REPLYRATE',
  'REPUTATION.INSIGHTS.DISTRIBUTION': 'REPUTATION.INSIGHTS.DISTRIBUTION',
  'REPUTATION.INSIGHTS.COMPETITORSMAP': 'REPUTATION.INSIGHTS.COMPETITORSMAP',
  'REPUTATION.INSIGHTS.TREND': 'REPUTATION.INSIGHTS.TREND',
  'REPUTATION.INSIGHTS.EXTENDED': 'REPUTATION.INSIGHTS.EXTENDED',
  'REPUTATION.INSIGHTS.REVIEWSANALYSIS': 'REPUTATION.INSIGHTS.REVIEWSANALYSIS',
  'REPUTATION.WIDGETS.REPUTATIONWIDGET': 'REPUTATION.WIDGETS.REPUTATIONWIDGET',
  'REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET': 'REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET',
  'AGENCY.ACCOUNTS.MANAGE': 'AGENCY.ACCOUNTS.MANAGE',
  'AGENCY.TOOLS': 'AGENCY.TOOLS',
  'SETUP.COMMON': 'SETUP.COMMON',
  'SETUP.COMMON.LOCATIONS': 'SETUP.COMMON.LOCATIONS',
  'SETUP.COMMON.KEYWORDS': 'SETUP.COMMON.KEYWORDS',
  'SETUP.COMMON.COMPETITORS': 'SETUP.COMMON.COMPETITORS',
};

export const AppliedFeatureFlagNameStrict = {
  'COMMON.SIDENAV': 'COMMON.SIDENAV',
  'COMMON.SIDENAV.OVERVIEW': 'COMMON.SIDENAV.OVERVIEW',
  'COMMON.SIDENAV.SEO': 'COMMON.SIDENAV.SEO',
  'COMMON.SIDENAV.SEO.DASHBOARD': 'COMMON.SIDENAV.SEO.DASHBOARD',
  'COMMON.SIDENAV.SEO.TASKS': 'COMMON.SIDENAV.SEO.TASKS',
  'COMMON.SIDENAV.SEO.INSIGHTS': 'COMMON.SIDENAV.SEO.INSIGHTS',
  'COMMON.SIDENAV.PRESENCE': 'COMMON.SIDENAV.PRESENCE',
  'COMMON.SIDENAV.PRESENCE.DSHBOARD': 'COMMON.SIDENAV.PRESENCE.DSHBOARD',
  'COMMON.SIDENAV.PRESENCE.PROFILE': 'COMMON.SIDENAV.PRESENCE.PROFILE',
  'COMMON.SIDENAV.PRESENCE.PROFILEFINETUNING': 'COMMON.SIDENAV.PRESENCE.PROFILEFINETUNING',
  'COMMON.SIDENAV.PRESENCE.LISTINGS': 'COMMON.SIDENAV.PRESENCE.LISTINGS',
  'COMMON.SIDENAV.PRESENCE.INSIGHTS': 'COMMON.SIDENAV.PRESENCE.INSIGHTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.DASHBOARD': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.DASHBOARD',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.CHAT': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.CHAT',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.POSTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.POSTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.EVENTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.EVENTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.OFFERS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.OFFERS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PRODUCTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PRODUCTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.BOOSTS': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.BOOSTS',
  'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PLANNER': 'COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PLANNER',
  'COMMON.SIDENAV.REPUTATION': 'COMMON.SIDENAV.REPUTATION',
  'COMMON.SIDENAV.REPUTATION.REVIEWS': 'COMMON.SIDENAV.REPUTATION.REVIEWS',
  'COMMON.SIDENAV.REPUTATION.REPLYTEMPLATES': 'COMMON.SIDENAV.REPUTATION.REPLYTEMPLATES',
  'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER': 'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER',
  'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.CUSTOMERS': 'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.CUSTOMERS',
  'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.PRINT': 'COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.PRINT',
  'COMMON.SIDENAV.REPUTATION.INSIGHTS': 'COMMON.SIDENAV.REPUTATION.INSIGHTS',
  'COMMON.SIDENAV.REPUTATION.WIDGETS.REPUTATIONWIDGET': 'COMMON.SIDENAV.REPUTATION.WIDGETS.REPUTATIONWIDGET',
  'COMMON.SIDENAV.REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET':
    'COMMON.SIDENAV.REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET',
  'COMMON.SIDENAV.REPUTATION.REVIEWSOURCES': 'COMMON.SIDENAV.REPUTATION.REVIEWSOURCES',
  'COMMON.SIDENAV.REPUTATION.MENTIONS': 'COMMON.SIDENAV.REPUTATION.MENTIONS',
  'COMMON.SIDENAV.ADS': 'COMMON.SIDENAV.ADS',
  'COMMON.SIDENAV.ADS.DASHBOARD': 'COMMON.SIDENAV.ADS.DASHBOARD',
  'COMMON.SIDENAV.ADS.BUDGET': 'COMMON.SIDENAV.ADS.BUDGET',
  'COMMON.SIDENAV.ADS.GOOGLE': 'COMMON.SIDENAV.ADS.GOOGLE',
  'COMMON.SIDENAV.ADS.SOCIAL': 'COMMON.SIDENAV.ADS.SOCIAL',
  'COMMON.SIDENAV.SETTINGS': 'COMMON.SIDENAV.SETTINGS',
  'COMMON.SIDENAV.BLOG': 'COMMON.SIDENAV.BLOG',
  'COMMON.TOPNAV': 'COMMON.TOPNAV',
  'COMMON.TOPNAV.MANAGEPROJECTS': 'COMMON.TOPNAV.MANAGEPROJECTS',
  'COMMON.TOPNAV.ACCOUNT': 'COMMON.TOPNAV.ACCOUNT',
  'COMMON.TOPNAV.JUMPSTART': 'COMMON.TOPNAV.JUMPSTART',
  'COMMON.JUMPSTART': 'COMMON.JUMPSTART',
  'COMMON.SUPPORT': 'COMMON.SUPPORT',
  'COMMON.SUPPORT.PREMIUM': 'COMMON.SUPPORT.PREMIUM',
  'AI.BUDGET': 'AI.BUDGET',
  'SEO.RANKINGS': 'SEO.RANKINGS',
  'SEO.RANKINGS.MAPS': 'SEO.RANKINGS.MAPS',
  'SEO.INSIGHTS.LVI': 'SEO.INSIGHTS.LVI',
  'SEO.INSIGHTS.RANKINGS.SEARCH': 'SEO.INSIGHTS.RANKINGS.SEARCH',
  'SEO.INSIGHTS.RANKINGS.MAPS': 'SEO.INSIGHTS.RANKINGS.MAPS',
  'SEO.INSIGHTS.RANKINGS.KEYWORD_DETAILS': 'SEO.INSIGHTS.RANKINGS.KEYWORD_DETAILS',
  'SEO.INSIGHTS.RANKINGS.COMPETITORS': 'SEO.INSIGHTS.RANKINGS.COMPETITORS',
  'SEO.TASKS': 'SEO.TASKS',
  'RADAR.FEED': 'RADAR.FEED',
  'ADS.GOOGLE.CAMPAIGN.CREATE': 'ADS.GOOGLE.CAMPAIGN.CREATE',
  'ADS.GOOGLE.CAMPAIGN.BUDGET': 'ADS.GOOGLE.CAMPAIGN.BUDGET',
  'ADS.GOOGLE.CAMPAIGN.LAUNCH': 'ADS.GOOGLE.CAMPAIGN.LAUNCH',
  'PRESENCE.LVI': 'PRESENCE.LVI',
  'PRESENCE.DSHBOARD.NBA': 'PRESENCE.DSHBOARD.NBA',
  'PRESENCE.DSHBOARD.LVI': 'PRESENCE.DSHBOARD.LVI',
  'PRESENCE.DSHBOARD.TOPRANKINGS.SEARCH': 'PRESENCE.DSHBOARD.TOPRANKINGS.SEARCH',
  'PRESENCE.DSHBOARD.TOPRANKINGS.MAPS': 'PRESENCE.DSHBOARD.TOPRANKINGS.MAPS',
  'PRESENCE.DSHBOARD.COMPETITORSMAP': 'PRESENCE.DSHBOARD.COMPETITORSMAP',
  'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING': 'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING',
  'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING.LISTINGSCHECKER': 'PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING.LISTINGSCHECKER',
  'PRESENCE.DSHBOARD.ENGAGEMENT': 'PRESENCE.DSHBOARD.ENGAGEMENT',
  'PRESENCE.DSHBOARD.ENGAGEMENT.PLANNER': 'PRESENCE.DSHBOARD.ENGAGEMENT.PLANNER',
  'PRESENCE.PROFILE.DETAILS': 'PRESENCE.PROFILE.DETAILS',
  'PRESENCE.PROFILE.ADDRESS': 'PRESENCE.PROFILE.ADDRESS',
  'PRESENCE.PROFILE.OPENINGHOURS': 'PRESENCE.PROFILE.OPENINGHOURS',
  'PRESENCE.PROFILE.CATEGORIES': 'PRESENCE.PROFILE.CATEGORIES',
  'PRESENCE.PROFILE.DESCRIPTION': 'PRESENCE.PROFILE.DESCRIPTION',
  'PRESENCE.PROFILE.MEDIAITEMS': 'PRESENCE.PROFILE.MEDIAITEMS',
  'PRESENCE.PROFILEFINETUNING.SERVICEITEMS': 'PRESENCE.PROFILEFINETUNING.SERVICEITEMS',
  'PRESENCE.PROFILEFINETUNING.ATTRIBUTES': 'PRESENCE.PROFILEFINETUNING.ATTRIBUTES',
  'PRESENCE.LISTINGS.LISTINGSERVICES': 'PRESENCE.LISTINGS.LISTINGSERVICES',
  'PRESENCE.LISTINGS.LISTINGSERVICES.GOOGLE': 'PRESENCE.LISTINGS.LISTINGSERVICES.GOOGLE',
  'PRESENCE.LISTINGS.LISTINGSERVICES.FACEBOOK': 'PRESENCE.LISTINGS.LISTINGSERVICES.FACEBOOK',
  'PRESENCE.LISTINGS.LISTINGSERVICES.INSTAGRAM': 'PRESENCE.LISTINGS.LISTINGSERVICES.INSTAGRAM',
  'PRESENCE.LISTINGS.LISTINGSERVICES.UBERALL': 'PRESENCE.LISTINGS.LISTINGSERVICES.UBERALL',
  'PRESENCE.LISTINGS.LISTINGSERVICES.YEXT': 'PRESENCE.LISTINGS.LISTINGSERVICES.YEXT',
  'PRESENCE.LISTINGS.LISTINGSERVICES.LINKEDIN': 'PRESENCE.LISTINGS.LISTINGSERVICES.LINKEDIN',
  'PRESENCE.LISTINGS.LISTINGSERVICES.X': 'PRESENCE.LISTINGS.LISTINGSERVICES.X',
  'PRESENCE.LISTINGS.LISTINGSCHECKER': 'PRESENCE.LISTINGS.LISTINGSCHECKER',
  'PRESENCE.ENGAGEMENT.CHAT': 'PRESENCE.ENGAGEMENT.CHAT',
  'PRESENCE.ENGAGEMENT.EVENTS': 'PRESENCE.ENGAGEMENT.EVENTS',
  'PRESENCE.ENGAGEMENT.EVENTS.AI': 'PRESENCE.ENGAGEMENT.EVENTS.AI',
  'PRESENCE.ENGAGEMENT.POSTS': 'PRESENCE.ENGAGEMENT.POSTS',
  'PRESENCE.ENGAGEMENT.POSTS.AI': 'PRESENCE.ENGAGEMENT.POSTS.AI',
  'PRESENCE.ENGAGEMENT.POSTS.AI.COMPETITORS': 'PRESENCE.ENGAGEMENT.POSTS.AI.COMPETITORS',
  'PRESENCE.ENGAGEMENT.POSTS.SCHEDULING': 'PRESENCE.ENGAGEMENT.POSTS.SCHEDULING',
  'PRESENCE.ENGAGEMENT.BOOSTS': 'PRESENCE.ENGAGEMENT.BOOSTS',
  'PRESENCE.ENGAGEMENT.BOOSTS.BUDGET': 'PRESENCE.ENGAGEMENT.BOOSTS.BUDGET',
  'PRESENCE.ENGAGEMENT.PLANNER': 'PRESENCE.ENGAGEMENT.PLANNER',
  'PRESENCE.ENGAGEMENT.PLANNER.ADVANCEDSCHEDULING': 'PRESENCE.ENGAGEMENT.PLANNER.ADVANCEDSCHEDULING',
  'PRESENCE.ENGAGEMENT.POSTS.AI.IMAGES': 'PRESENCE.ENGAGEMENT.POSTS.AI.IMAGES',
  'PRESENCE.INSIGHTS.LVI': 'PRESENCE.INSIGHTS.LVI',
  'PRESENCE.INSIGHTS.TOPRANKINGS.SEARCH': 'PRESENCE.INSIGHTS.TOPRANKINGS.SEARCH',
  'PRESENCE.INSIGHTS.TOPRANKINGS.MAPS': 'PRESENCE.INSIGHTS.TOPRANKINGS.MAPS',
  'PRESENCE.INSIGHTS.COMPETITORSMAP': 'PRESENCE.INSIGHTS.COMPETITORSMAP',
  'PRESENCE.INSIGHTS.GOOGLE': 'PRESENCE.INSIGHTS.GOOGLE',
  'PRESENCE.INSIGHTS.GOOGLE.INTERACTIONS': 'PRESENCE.INSIGHTS.GOOGLE.INTERACTIONS',
  'PRESENCE.INSIGHTS.GOOGLE.VIEWS': 'PRESENCE.INSIGHTS.GOOGLE.VIEWS',
  'PRESENCE.INSIGHTS.GOOGLE.PLATFORMS': 'PRESENCE.INSIGHTS.GOOGLE.PLATFORMS',
  'PRESENCE.INSIGHTS.GOOGLE.MEDIAITEM': 'PRESENCE.INSIGHTS.GOOGLE.MEDIAITEM',
  'PRESENCE.INSIGHTS.RANKINGS.SEARCH': 'PRESENCE.INSIGHTS.RANKINGS.SEARCH',
  'PRESENCE.INSIGHTS.RANKINGS.MAPS': 'PRESENCE.INSIGHTS.RANKINGS.MAPS',
  'REPUTATION.DSHBOARD.NBA': 'REPUTATION.DSHBOARD.NBA',
  'REPUTATION.DSHBOARD.SUMMARY': 'REPUTATION.DSHBOARD.SUMMARY',
  'REPUTATION.DSHBOARD.CLUSTERS': 'REPUTATION.DSHBOARD.CLUSTERS',
  'REPUTATION.DSHBOARD.CLUSTERS.GRADIENTCHART': 'REPUTATION.DSHBOARD.CLUSTERS.GRADIENTCHART',
  'REPUTATION.DSHBOARD.CLUSTERS.STARAVERAGE': 'REPUTATION.DSHBOARD.CLUSTERS.STARAVERAGE',
  'REPUTATION.DSHBOARD.CLUSTERS.REVIEWVOLUME': 'REPUTATION.DSHBOARD.CLUSTERS.REVIEWVOLUME',
  'REPUTATION.DSHBOARD.CLUSTERS.REVIEWRECENCY': 'REPUTATION.DSHBOARD.CLUSTERS.REVIEWRECENCY',
  'REPUTATION.DSHBOARD.CLUSTERS.REVIEWLENGTH': 'REPUTATION.DSHBOARD.CLUSTERS.REVIEWLENGTH',
  'REPUTATION.DSHBOARD.CLUSTERS.REPLYRATE': 'REPUTATION.DSHBOARD.CLUSTERS.REPLYRATE',
  'REPUTATION.DSHBOARD.REVIEWSTATUS': 'REPUTATION.DSHBOARD.REVIEWSTATUS',
  'REPUTATION.DSHBOARD.RATINGSANDREVIEWS': 'REPUTATION.DSHBOARD.RATINGSANDREVIEWS',
  'REPUTATION.DSHBOARD.REVIEWSOURCES': 'REPUTATION.DSHBOARD.REVIEWSOURCES',
  'REPUTATION.REVIEWS': 'REPUTATION.REVIEWS',
  'REPUTATION.REVIEWS.REPLY': 'REPUTATION.REVIEWS.REPLY',
  'REPUTATION.REVIEWS.YEXT.REPLY': 'REPUTATION.REVIEWS.YEXT.REPLY',
  'REPUTATION.REVIEWS.REPLY.AI': 'REPUTATION.REVIEWS.REPLY.AI',
  'REPUTATION.REPLYTEMPLATES.AI': 'REPUTATION.REPLYTEMPLATES.AI',
  'REPUTATION.REVIEWBOOSTER': 'REPUTATION.REVIEWBOOSTER',
  'REPUTATION.REVIEWBOOSTER.MAIL': 'REPUTATION.REVIEWBOOSTER.MAIL',
  'REPUTATION.REVIEWBOOSTER.SMS': 'REPUTATION.REVIEWBOOSTER.SMS',
  'REPUTATION.REVIEWBOOSTER.AI': 'REPUTATION.REVIEWBOOSTER.AI',
  'REPUTATION.REVIEWBOOSTER.PRINT': 'REPUTATION.REVIEWBOOSTER.PRINT',
  'REPUTATION.REVIEWSOURCES': 'REPUTATION.REVIEWSOURCES',
  'REPUTATION.MENTIONS': 'REPUTATION.MENTIONS',
  'REPUTATION.INSIGHTS.SUMMARY': 'REPUTATION.INSIGHTS.SUMMARY',
  'REPUTATION.CINSIGHTS.CLUSTERS': 'REPUTATION.CINSIGHTS.CLUSTERS',
  'REPUTATION.INSIGHTS.CLUSTERS.GRADIENTCHART': 'REPUTATION.INSIGHTS.CLUSTERS.GRADIENTCHART',
  'REPUTATION.INSIGHTS.CLUSTERS.STARAVERAGE': 'REPUTATION.INSIGHTS.CLUSTERS.STARAVERAGE',
  'REPUTATION.INSIGHTS.CLUSTERS.REVIEWVOLUME': 'REPUTATION.INSIGHTS.CLUSTERS.REVIEWVOLUME',
  'REPUTATION.INSIGHTS.CLUSTERS.REVIEWRECENCY': 'REPUTATION.INSIGHTS.CLUSTERS.REVIEWRECENCY',
  'REPUTATION.INSIGHTS.CLUSTERS.REVIEWLENGTH': 'REPUTATION.INSIGHTS.CLUSTERS.REVIEWLENGTH',
  'REPUTATION.INSIGHTS.CLUSTERS.REPLYRATE': 'REPUTATION.INSIGHTS.CLUSTERS.REPLYRATE',
  'REPUTATION.INSIGHTS.DISTRIBUTION': 'REPUTATION.INSIGHTS.DISTRIBUTION',
  'REPUTATION.INSIGHTS.COMPETITORSMAP': 'REPUTATION.INSIGHTS.COMPETITORSMAP',
  'REPUTATION.INSIGHTS.TREND': 'REPUTATION.INSIGHTS.TREND',
  'REPUTATION.INSIGHTS.EXTENDED': 'REPUTATION.INSIGHTS.EXTENDED',
  'REPUTATION.INSIGHTS.REVIEWSANALYSIS': 'REPUTATION.INSIGHTS.REVIEWSANALYSIS',
  'REPUTATION.WIDGETS.REPUTATIONWIDGET': 'REPUTATION.WIDGETS.REPUTATIONWIDGET',
  'REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET': 'REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET',
  'AGENCY.ACCOUNTS.MANAGE': 'AGENCY.ACCOUNTS.MANAGE',
  'AGENCY.TOOLS': 'AGENCY.TOOLS',
  'SETUP.COMMON': 'SETUP.COMMON',
  'SETUP.COMMON.LOCATIONS': 'SETUP.COMMON.LOCATIONS',
  'SETUP.COMMON.KEYWORDS': 'SETUP.COMMON.KEYWORDS',
  'SETUP.COMMON.COMPETITORS': 'SETUP.COMMON.COMPETITORS',
} as const;

export const AppliedFeatureFlagObjectType = {
  App_Domain_Product_Entities_Products_FeatureFlags_AppliedFeatureFlag:
    'App\\Domain\\Product\\Entities\\Products\\FeatureFlags\\AppliedFeatureFlag',
};

export const AppliedFeatureFlagObjectTypeStrict = {
  App_Domain_Product_Entities_Products_FeatureFlags_AppliedFeatureFlag:
    'App\\Domain\\Product\\Entities\\Products\\FeatureFlags\\AppliedFeatureFlag',
} as const;

export type AppliedFeatureFlag = {
  /**
   * Wheather the FeatureFlag is available through upgrade of ProductRateplan or the upgrade offers a higher value option through it's FeatureFlagSetting
   */
  hasUpgrades?: boolean;
  availableUpgrades?: AppliedFeatureFlagUpgrades;
  /**
   * The name of the FeatureFlag
   *  Allowed Values:
   * -   `COMMON.SIDENAV`: Display SideNav
   * -   `COMMON.SIDENAV.OVERVIEW`: Display SideNav > Overview
   * -   `COMMON.SIDENAV.SEO`: Display SideNav > SEO
   * -   `COMMON.SIDENAV.SEO.DASHBOARD`: Display SideNav > SEO > Dashboard
   * -   `COMMON.SIDENAV.SEO.TASKS`: Display SideNav > SEO > Tasks
   * -   `COMMON.SIDENAV.SEO.INSIGHTS`: Display SideNav > SEO >Insights
   * -   `COMMON.SIDENAV.PRESENCE`: Display SideNav > Presence
   * -   `COMMON.SIDENAV.PRESENCE.DSHBOARD`: Display SideNav > Presence > Dashboard
   * -   `COMMON.SIDENAV.PRESENCE.PROFILE`: Display SideNav > Presence > Business Profile
   * -   `COMMON.SIDENAV.PRESENCE.PROFILEFINETUNING`: Display SideNav > Presence > Profile finetuning
   * -   `COMMON.SIDENAV.PRESENCE.LISTINGS`: Display SideNav > Presence > Listings (and publishing)
   * -   `COMMON.SIDENAV.PRESENCE.INSIGHTS`: Display SideNav > Presence > Insights
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT`: Display SideNav > Presence > Engagement
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.DASHBOARD`: Display SideNav > Presence > Engagement > Dashboard
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.CHAT`: Display SideNav > Presence > Engagement > Chat
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.POSTS`: Display SideNav > Presence > Engagement > Posts
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.EVENTS`: Display SideNav > Presence > Engagement > Events
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.OFFERS`: Display SideNav > Presence > Engagement > Offers
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PRODUCTS`: Display SideNav > Presence > Engagement > Products
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.BOOSTS`: Display SideNav > Presence > Engagement > Boosts
   * -   `COMMON.SIDENAV.PRESENCE.ENGAGEMENT.PLANNER`: Display SideNav > Presence > Engagement > Planner
   * -   `COMMON.SIDENAV.REPUTATION`: Display SideNav > Reputation
   * -   `COMMON.SIDENAV.REPUTATION.REVIEWS`: Display SideNav > Reputation > Reviews
   * -   `COMMON.SIDENAV.REPUTATION.REPLYTEMPLATES`: Display SideNav > Reputation > Reply Templates
   * -   `COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER`: Display SideNav > Reputation > Reviews Booster
   * -   `COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.CUSTOMERS`: Display SideNav > Reputation > Reviews Booster > Customer List
   * -   `COMMON.SIDENAV.REPUTATION.REVIEWBOOSTER.PRINT`: Display SideNav > Reputation > Reviews Booster > Print Materials
   * -   `COMMON.SIDENAV.REPUTATION.INSIGHTS`: Display SideNav > Reputation > Insights
   * -   `COMMON.SIDENAV.REPUTATION.WIDGETS.REPUTATIONWIDGET`: Display SideNav > Reputation > Widgets > Reputation Widget
   * -   `COMMON.SIDENAV.REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET`: Display SideNav > Reputation > Widgets > Reviews Collector Widget
   * -   `COMMON.SIDENAV.REPUTATION.REVIEWSOURCES`: Display SideNav > Reputation > Review Sources
   * -   `COMMON.SIDENAV.REPUTATION.MENTIONS`: Display SideNav > Reputation > Mentions
   * -   `COMMON.SIDENAV.ADS`: Display SideNav > Ads
   * -   `COMMON.SIDENAV.ADS.DASHBOARD`: Display SideNav > Ads > Dashboard
   * -   `COMMON.SIDENAV.ADS.BUDGET`: Display SideNav > Ads > Budget
   * -   `COMMON.SIDENAV.ADS.GOOGLE`: Display SideNav > Ads > Google
   * -   `COMMON.SIDENAV.ADS.SOCIAL`: Display SideNav > Ads > Social
   * -   `COMMON.SIDENAV.SETTINGS`: Display SideNav > Settings
   * -   `COMMON.SIDENAV.BLOG`: Display SideNav > Blog
   * -   `COMMON.TOPNAV`: Display TopNav
   * -   `COMMON.TOPNAV.MANAGEPROJECTS`: Display TopNav > Manage projects
   * -   `COMMON.TOPNAV.ACCOUNT`: Display TopNav > Account
   * -   `COMMON.TOPNAV.JUMPSTART`: Display TopNav > Jumpstart
   * -   `COMMON.JUMPSTART`: Has Jump Start feature
   * -   `COMMON.SUPPORT`: Display default support system, has detail FeatureFlagSetting
   * -   `COMMON.SUPPORT.PREMIUM`: Has premium support feature
   * -   `AI.BUDGET`: Ai Budget
   * -   `SEO.RANKINGS`: Has SEO Rankings feature
   * -   `SEO.RANKINGS.MAPS`: Display SEO Maps rankings feature
   * -   `SEO.INSIGHTS.LVI`: Display SEO > Insights > LVI
   * -   `SEO.INSIGHTS.RANKINGS.SEARCH`: Display SEO > Insights > Search rankings
   * -   `SEO.INSIGHTS.RANKINGS.MAPS`: Display SEO > Insights > Maps rankings
   * -   `SEO.INSIGHTS.RANKINGS.KEYWORD_DETAILS`: Display SEO > Insights > Rankings > Keyword Details
   * -   `SEO.INSIGHTS.RANKINGS.COMPETITORS`: Display SEO > Insights > Rankings > Competitors rankings
   * -   `SEO.TASKS`: Has SEO Tasks feature, has detail FeatureFlagSetting
   * -   `RADAR.FEED`: Has Radar Feed
   * -   `ADS.GOOGLE.CAMPAIGN.CREATE`: Can create a Google Ads Campaign (does not include launching the campaign)
   * -   `ADS.GOOGLE.CAMPAIGN.BUDGET`: Can view and modify Google Ads Campaign Budget
   * -   `ADS.GOOGLE.CAMPAIGN.LAUNCH`: Can launch a Google Ads Campaign
   * -   `PRESENCE.LVI`: Has Local Visibility Index (LVI)
   * -   `PRESENCE.DSHBOARD.NBA`: Display Presence > Dashboard > Next Best Actions (NBAs)
   * -   `PRESENCE.DSHBOARD.LVI`: Display Presence > Dashboard > Local Visibility Index (LAVI)
   * -   `PRESENCE.DSHBOARD.TOPRANKINGS.SEARCH`: Display Presence > Dashboard > Top search-rankings
   * -   `PRESENCE.DSHBOARD.TOPRANKINGS.MAPS`: Display Presence > Dashboard > Top maps-rankings
   * -   `PRESENCE.DSHBOARD.COMPETITORSMAP`: Display Presence > Dashboard > Competitors map on
   * -   `PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING`: Display Presence > Dashboard > Listings and publising overview
   * -   `PRESENCE.DSHBOARD.LISTINGSANDPUBLISHING.LISTINGSCHECKER`: Has Presence > Dashboard > Listings and publising > Listings Checker
   * -   `PRESENCE.DSHBOARD.ENGAGEMENT`: Display Presence > Dashboard > Engagement
   * -   `PRESENCE.DSHBOARD.ENGAGEMENT.PLANNER`: Display Presence > Dashboard > Engagement > Planner
   * -   `PRESENCE.PROFILE.DETAILS`: Display Presence > Business profile > Business details
   * -   `PRESENCE.PROFILE.ADDRESS`: Display Presence > Business profile > Business address
   * -   `PRESENCE.PROFILE.OPENINGHOURS`: Display Presence > Business profile > Opening times
   * -   `PRESENCE.PROFILE.CATEGORIES`: Display Presence > Business profile > Categories
   * -   `PRESENCE.PROFILE.DESCRIPTION`: Display Presence > Business profile > Description
   * -   `PRESENCE.PROFILE.MEDIAITEMS`: Display Presence > Business profile > Photo gellery
   * -   `PRESENCE.PROFILEFINETUNING.SERVICEITEMS`: Display Presence > Profile finetuning > Service items
   * -   `PRESENCE.PROFILEFINETUNING.ATTRIBUTES`: Display Presence > Profile finetuning > Attributes
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES`: Has Presence > Listing services feature
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES.GOOGLE`: Has Presence > Listing services > Google
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES.FACEBOOK`: Has Presence > Listing services > Facebook
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES.INSTAGRAM`: Has Presence > Listing services > Instagram
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES.UBERALL`: Has Presence > Listing services > Uberall
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES.YEXT`: Has Presence > Listing services > Yext
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES.LINKEDIN`: Has Presence > Listing services > LinkedIn
   * -   `PRESENCE.LISTINGS.LISTINGSERVICES.X`: Has Presence > Listing services > X
   * -   `PRESENCE.LISTINGS.LISTINGSCHECKER`: Has Presence > Listings > Listings Checker
   * -   `PRESENCE.ENGAGEMENT.CHAT`: Display Presence > Engagement > Chat
   * -   `PRESENCE.ENGAGEMENT.EVENTS`: Display Presence > Engagement > Events
   * -   `PRESENCE.ENGAGEMENT.EVENTS.AI`: Display Presence > Engagement > Events > Generate content by AI
   * -   `PRESENCE.ENGAGEMENT.POSTS`: Display Presence > Engagement > Posts
   * -   `PRESENCE.ENGAGEMENT.POSTS.AI`: Display Presence > Engagement > Posts > Generate content by AI
   * -   `PRESENCE.ENGAGEMENT.POSTS.AI.COMPETITORS`: Display Presence > Engagement > Posts > Generate content by AI based on competitors
   * -   `PRESENCE.ENGAGEMENT.POSTS.SCHEDULING`: Display Presence > Engagement > Posts > Scheduling
   * -   `PRESENCE.ENGAGEMENT.BOOSTS`: Display Presence > Engagement > Boosts
   * -   `PRESENCE.ENGAGEMENT.BOOSTS.BUDGET`: Configure Presence > Engagement > Boosts > Budget
   * -   `PRESENCE.ENGAGEMENT.PLANNER`: Configure Presence > Engagement > Planner
   * -   `PRESENCE.ENGAGEMENT.PLANNER.ADVANCEDSCHEDULING`: Configure Presence > Engagement > Planner > Advanced Scheduling
   * -   `PRESENCE.ENGAGEMENT.POSTS.AI.IMAGES`: Configure Presence > Engagement > Posts > AI > Generate Images With AI
   * -   `PRESENCE.INSIGHTS.LVI`: Display Presence > Insights > LVI
   * -   `PRESENCE.INSIGHTS.TOPRANKINGS.SEARCH`: Display Presence > Insights > top search-rankings in presence insisghts
   * -   `PRESENCE.INSIGHTS.TOPRANKINGS.MAPS`: Display Presence > Insights > top maps-rankings on presence insights
   * -   `PRESENCE.INSIGHTS.COMPETITORSMAP`: Display Presence > Insights > competitors map on presence insights
   * -   `PRESENCE.INSIGHTS.GOOGLE`: Display Presence > Insights > Google Business Profile related statistics
   * -   `PRESENCE.INSIGHTS.GOOGLE.INTERACTIONS`: Display Presence > Insights > Google Business Profile > Customer interactions
   * -   `PRESENCE.INSIGHTS.GOOGLE.VIEWS`: Display Presence > Insights > Google Business Profile > Customer views
   * -   `PRESENCE.INSIGHTS.GOOGLE.PLATFORMS`: Display Presence > Insights > Google Business Profile > Platforms
   * -   `PRESENCE.INSIGHTS.GOOGLE.MEDIAITEM`: Display Presence > Insights > Google Business Profile > Media / images
   * -   `PRESENCE.INSIGHTS.RANKINGS.SEARCH`: Display Presence > Insights > Search rankings
   * -   `PRESENCE.INSIGHTS.RANKINGS.MAPS`: Display Presence > Insights > Maps rankings
   * -   `REPUTATION.DSHBOARD.NBA`: Display Reputation > Dashboard > Next Best Actions (NBAs)
   * -   `REPUTATION.DSHBOARD.SUMMARY`: Display Reputation > Dashboard > Summary (Your reputation at a glance)
   * -   `REPUTATION.DSHBOARD.CLUSTERS`: Display Reputation > Dashboard > Clusters
   * -   `REPUTATION.DSHBOARD.CLUSTERS.GRADIENTCHART`: Display Reputation > Dashboard > Clusters > GradientChart
   * -   `REPUTATION.DSHBOARD.CLUSTERS.STARAVERAGE`: Display Reputation > Dashboard > Clusters > Star Average
   * -   `REPUTATION.DSHBOARD.CLUSTERS.REVIEWVOLUME`: Display Reputation > Dashboard > Clusters > Review Volume
   * -   `REPUTATION.DSHBOARD.CLUSTERS.REVIEWRECENCY`: Display Reputation > Dashboard > Clusters > Review Recency
   * -   `REPUTATION.DSHBOARD.CLUSTERS.REVIEWLENGTH`: Display Reputation > Dashboard > Clusters > Review Length
   * -   `REPUTATION.DSHBOARD.CLUSTERS.REPLYRATE`: Display Reputation > Dashboard > Clusters > Reply Rate
   * -   `REPUTATION.DSHBOARD.REVIEWSTATUS`: Display Reputation > Dashboard > Review Status
   * -   `REPUTATION.DSHBOARD.RATINGSANDREVIEWS`: Display Reputation > Dashboard > Ratings and Reviews
   * -   `REPUTATION.DSHBOARD.REVIEWSOURCES`: Display Reputation > Dashboard > Review Sources
   * -   `REPUTATION.REVIEWS`: Display Reputation > Reviews
   * -   `REPUTATION.REVIEWS.REPLY`: Display Reputation > Reviews > Reply
   * -   `REPUTATION.REVIEWS.YEXT.REPLY`: Display Reputation > Reviews > Yext > Reply
   * -   `REPUTATION.REVIEWS.REPLY.AI`: Display Reputation > Reviews > Reply with AI aid
   * -   `REPUTATION.REPLYTEMPLATES.AI`: Display Reputation > Reply Templates > Manage AI reply options
   * -   `REPUTATION.REVIEWBOOSTER`: Reputation > Reviews Booster Feature
   * -   `REPUTATION.REVIEWBOOSTER.MAIL`: Reputation > Reviews Booster > Mail Feature
   * -   `REPUTATION.REVIEWBOOSTER.SMS`: Reputation > Reviews Booster > SMS Feature
   * -   `REPUTATION.REVIEWBOOSTER.AI`: Reputation > Reviews Booster > AI text feature
   * -   `REPUTATION.REVIEWBOOSTER.PRINT`: Reputation > Reviews Booster > Print Materials
   * -   `REPUTATION.REVIEWSOURCES`: Display Reputation > Review Sources
   * -   `REPUTATION.MENTIONS`: Display Reputation > Mentions
   * -   `REPUTATION.INSIGHTS.SUMMARY`: Display Reputation > Insights > Summary (Your reputation at a glance)
   * -   `REPUTATION.CINSIGHTS.CLUSTERS`: Display Reputation > Insights > Clusters
   * -   `REPUTATION.INSIGHTS.CLUSTERS.GRADIENTCHART`: Display Reputation > Insights > Clusters > GradientChart
   * -   `REPUTATION.INSIGHTS.CLUSTERS.STARAVERAGE`: Display Reputation > Insights > Clusters > Star Average
   * -   `REPUTATION.INSIGHTS.CLUSTERS.REVIEWVOLUME`: Display Reputation > Insights > Clusters > Review Volume
   * -   `REPUTATION.INSIGHTS.CLUSTERS.REVIEWRECENCY`: Display Reputation > Insights > Clusters > Review Recency
   * -   `REPUTATION.INSIGHTS.CLUSTERS.REVIEWLENGTH`: Display Reputation > Insights > Clusters > Review Length
   * -   `REPUTATION.INSIGHTS.CLUSTERS.REPLYRATE`: Display Reputation > Insights > Clusters > Reply Rate
   * -   `REPUTATION.INSIGHTS.DISTRIBUTION`: Display Reputation > Insights > Distribution (Competitor Gauss Chart)
   * -   `REPUTATION.INSIGHTS.COMPETITORSMAP`: Display Reputation > Insights > Competitors Map
   * -   `REPUTATION.INSIGHTS.TREND`: Display Reputation > Insights > Trend
   * -   `REPUTATION.INSIGHTS.EXTENDED`: Display Reputation > Insights > Extended (geeky details...)
   * -   `REPUTATION.INSIGHTS.REVIEWSANALYSIS`: Display Reputation > Insights > Reviews Analysis
   * -   `REPUTATION.WIDGETS.REPUTATIONWIDGET`: Display Reputation > Widgets > Reputation Widget
   * -   `REPUTATION.WIDGETS.REVIEWSCOLLECTORWIDGET`: Display Reputation > Widgets > Reviews Widget
   * -   `AGENCY.ACCOUNTS.MANAGE`: Display Angecy (Sub-)Accounts Management
   * -   `AGENCY.TOOLS`: Display Agency Tools
   * -   `SETUP.COMMON`: Setup > Common > Locations settings (amount of locations selectable)
   * -   `SETUP.COMMON.LOCATIONS`: Setup > Common > Locations settings (amount of locations selectable)
   * -   `SETUP.COMMON.KEYWORDS`: Setup > Common > Keywords settings (amount of keywords etc.)
   * -   `SETUP.COMMON.COMPETITORS`: Setup > Common > Competitors settings (amount of competitors etc.)
   *
   */
  name?: (typeof AppliedFeatureFlagName)[keyof typeof AppliedFeatureFlagName];
  /**
   * Describes usage and scope of this FeatureFlag
   */
  description?: string;
  /**
   * Wheather the FeatureFlag is available or not
   */
  available?: boolean;
  setting?:
    | AdsGoogleCampaignBudgetFeatureFlagSetting
    | MetaBoostCampaignBudgetFeatureFlagSetting
    | ListingServiceFeatureFlagSetting
    | FacebookFeatureFlagSetting
    | GoogleFeatureFlagSetting
    | UberallFeatureFlagSetting
    | YextFeatureFlagSetting
    | LinkedInFeatureFlagSetting
    | XFeatureFlagSetting
    | RadarFeedFeatureFlagSetting
    | SeoRankingsFeatureFlagSetting
    | SetupCommonCompetitorsFeatureFlagSetting
    | SetupCommonFeatureFlagSetting
    | SetupCommonKeywordsFeatureFlagSetting
    | SetupCommonLocationsFeatureFlagSetting
    | AIBudgetFeatureFlagSetting;
  /**
   * The fully qualified class name of the object
   */
  objectType: (typeof AppliedFeatureFlagObjectType)[keyof typeof AppliedFeatureFlagObjectType];
  /**
   * The internal identifier of the entity
   */
  id?: number;
};
