import type { EditorThemeClasses } from 'lexical';

import style from './LexicalTheme.module.scss';

export const LexicalTheme: EditorThemeClasses = {
  keyword: style.highlightedKeyword,
  blockCursor: style.blockCursor,
  characterLimit: style.characterLimit,
  code: style.code,
  codeHighlight: {
    atrule: style.tokenAttr,
    attr: style.tokenAttr,
    boolean: style.tokenProperty,
    builtin: style.tokenSelector,
    cdata: style.tokenComment,
    char: style.tokenSelector,
    class: style.tokenFunction,
    'class-name': style.tokenFunction,
    comment: style.tokenComment,
    constant: style.tokenProperty,
    deleted: style.tokenProperty,
    doctype: style.tokenComment,
    entity: style.tokenOperator,
    function: style.tokenFunction,
    important: style.tokenVariable,
    inserted: style.tokenSelector,
    keyword: style.tokenAttr,
    namespace: style.tokenVariable,
    number: style.tokenProperty,
    operator: style.tokenOperator,
    prolog: style.tokenComment,
    property: style.tokenProperty,
    punctuation: style.tokenPunctuation,
    regex: style.tokenVariable,
    selector: style.tokenSelector,
    string: style.tokenSelector,
    symbol: style.tokenProperty,
    tag: style.tokenProperty,
    url: style.tokenOperator,
    variable: style.tokenVariable,
  },
  embedBlock: {
    base: style.embedBlock,
    focus: style.embedBlockFocus,
  },
  hashtag: style.hashtag,
  heading: {
    h1: style.h1,
    h2: style.h2,
    h3: style.h3,
    h4: style.h4,
    h5: style.h5,
    h6: style.h6,
  },
  indent: style.indent,
  layoutContainer: style.layoutContaner,
  layoutItem: style.layoutItem,
  link: style.link,
  list: {
    listitem: style.listItem,
    listitemChecked: style.listItemChecked,
    listitemUnchecked: style.listItemUnchecked,
    nested: {
      listitem: style.nestedListItem,
    },
    olDepth: [style.ol1, style.ol2, style.ol3, style.ol4, style.ol5],
    ul: style.ul,
  },
  ltr: style.ltr,
  mark: style.mark,
  markOverlap: style.markOverlap,
  paragraph: style.paragraph,
  quote: style.quote,
  rtl: style.rtl,
  table: style.table,
  tableCell: style.tableCell,
  tableCellHeader: style.tableCellHeader,
  tableCellPrimarySelected: style.tableCellPrimarySelected,
  tableCellResizer: style.tableCellResizer,
  tableCellSelected: style.tableCellSelected,
  tableResizeRuler: style.tableCellResizeRuler,
  tableSelected: style.tableSelected,
  tableSelection: style.tableSelection,
  text: {
    bold: style.textBold,
    code: style.textCode,
    italic: style.textItalic,
    strikethrough: style.textStrikethrough,
    subscript: style.textSubscript,
    superscript: style.textSuperscript,
    underline: style.textUnderline,
    underlineStrikethrough: style.textUnderlineStrikethrough,
  },
};
